export const styles = {
  appContainer: {
    display: 'flex',
    flex: 1,
    height: '100vh',
    width: '100vw',
    backgroundColor: 'var(--bg-main)',
    overflow: 'hidden',
  },
  sidebar: {
    width: '280px',
    flexShrink: 0,
    backgroundColor: 'var(--bg-sidebar)',
    borderRight: '1px solid var(--border-color)',
    display: 'flex',
    flexDirection: 'column' as const,
    padding: '28px 20px',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '40px',
    paddingLeft: '6px',
  },
  logoBadge: {
    background: 'linear-gradient(135deg, #6366f1, #0ea5e9)',
    color: '#FFFFFF',
    fontFamily: 'Space Grotesk, sans-serif',
    fontWeight: 700,
    fontSize: '18px',
    padding: '8px 12px',
    borderRadius: '8px',
    boxShadow: '0 4px 15px rgba(99, 102, 241, 0.3)',
  },
  logoTitle: {
    fontFamily: 'Space Grotesk, sans-serif',
    fontSize: '22px',
    fontWeight: 700,
    color: 'var(--text-main)',
    letterSpacing: '-0.5px',
  },
  navList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    flex: 1,
  },
  navBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    background: 'transparent',
    border: 'none',
    color: 'var(--text-muted)',
    padding: '12px 16px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    fontWeight: 600,
    fontSize: '14px',
    textAlign: 'left' as const,
    transition: 'all 0.2s ease',
    width: '100%',
  },
  navBtnActive: {
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    color: 'var(--text-main)',
    border: '1px solid rgba(99, 102, 241, 0.2)',
  },
  subNavList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
    paddingLeft: '14px',
    borderLeft: '1px solid var(--border-color)',
    marginLeft: '26px',
    marginTop: '4px',
    marginBottom: '8px',
  },
  subNavBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'transparent',
    border: 'none',
    color: 'var(--text-muted)',
    padding: '8px 12px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    fontWeight: 500,
    fontSize: '13px',
    textAlign: 'left' as const,
    transition: 'all 0.2s ease',
    width: '100%',
  },
  subNavBtnActive: {
    backgroundColor: 'rgba(14, 165, 233, 0.08)',
    color: '#38BDF8',
    fontWeight: 600,
  },
  subNavIcon: {
    fontSize: '14px',
    opacity: 0.7,
  },
  exitBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    background: 'rgba(239, 68, 68, 0.05)',
    border: '1px solid rgba(239, 68, 68, 0.15)',
    color: '#fca5a5',
    padding: '12px 16px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    fontWeight: 600,
    fontSize: '14px',
    textAlign: 'left' as const,
    transition: 'all 0.2s ease',
    width: '100%',
    marginBottom: '20px',
  },
  navIcon: {
    fontSize: '18px',
  },
  footerSection: {
    borderTop: '1px solid var(--border-color)',
    paddingTop: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  avatar: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid var(--border-color)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
  },
  footerInfo: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  devName: {
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--text-main)',
  },
  devRole: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    marginTop: '2px',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
    minWidth: 0,
  },
  header: {
    paddingTop: '3px',
    paddingBottom: '3px',
    borderBottom: '1px solid var(--border-color)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: '40px',
    paddingRight: '40px',
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(12px)',
  },
  breadcrumb: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 500,
  },
  breadRoot: {
    color: 'var(--text-muted)',
  },
  breadDivider: {
    color: 'var(--border-color)',
  },
  breadActive: {
    color: 'var(--text-main)',
    fontWeight: 700,
  },
  indicatorContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'rgba(16, 185, 129, 0.08)',
    border: '1px solid rgba(16, 185, 129, 0.2)',
    padding: '4px 10px',
    borderRadius: '99px',
  },
  statusDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#10B981',
    boxShadow: '0 0 8px #10B981',
  },
  statusText: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#10B981',
    letterSpacing: '0.5px',
  },
  refreshBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid var(--border-color)',
    color: 'var(--text-main)',
    padding: '5px 12px',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 600,
    transition: 'all 0.2s',
  },
  viewBody: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '40px',
  },
  themeToggleBtn: {
    background: 'transparent',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: 'var(--text-muted)',
    transition: 'all 0.2s ease',
  },
};
