export const styles = {
  container: {
    width: '100%',
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: '360px 1fr',
    gap: '28px',
    alignItems: 'start',
  },
  formPanel: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '18px',
  },
  cardTitle: {
    fontSize: '18px',
  },
  editorPanel: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: '500px',
  },
  editorHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '16px',
    marginBottom: '20px',
  },
  workspaceBody: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  centered: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    padding: '40px',
  },
  emptyIcon: {
    fontSize: '44px',
    opacity: 0.3,
  },
  emptyText: {
    color: 'var(--text-main)',
    fontWeight: '700',
    fontSize: '14px',
  },
  loadingText: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#6366F1',
    letterSpacing: '0.5px',
  },
  loadingSubText: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    textAlign: 'center' as const,
  },
  questionsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  questionCard: {
    backgroundColor: 'var(--bg-sidebar)',
    border: '1px solid var(--border-color)',
    borderRadius: '12px',
    padding: '16px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '14px',
  },
  qHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badgesRow: {
    display: 'flex',
    gap: '8px',
  },
  qBadge: {
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
  },
  badgeEasy: {
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    color: '#10B981',
    border: '1px solid rgba(16, 185, 129, 0.2)',
  },
  badgeAvg: {
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    color: '#F59E0B',
    border: '1px solid rgba(245, 158, 11, 0.2)',
  },
  badgeDiff: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#EF4444',
    border: '1px solid rgba(239, 68, 68, 0.2)',
  },
  badgeCat: {
    backgroundColor: 'rgba(99, 102, 241, 0.1)',
    color: 'var(--accent-primary)',
    border: '1px solid rgba(99, 102, 241, 0.2)',
  },
  idInput: {
    background: 'transparent',
    border: 'none',
    borderBottom: '1px dashed var(--border-color)',
    fontFamily: 'Space Grotesk, sans-serif',
    fontWeight: 700,
    fontSize: '12px',
    color: 'var(--text-main)',
    padding: '2px 4px',
    width: '150px',
    borderRadius: 0,
  },
  textInput: {
    backgroundColor: 'var(--bg-main)',
    border: '1px solid var(--border-color)',
    color: 'var(--text-main)',
  },
  optionsSection: {
    gap: '8px',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
    marginTop: '6px',
  },
  optRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'var(--bg-main)',
    border: '1px solid var(--border-color)',
    borderRadius: '8px',
    paddingHorizontal: '8px',
  },
  optLabel: {
    fontSize: '10px',
    fontWeight: '800',
    color: 'var(--text-muted)',
    backgroundColor: 'var(--border-color)',
    width: '18px',
    height: '18px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    padding: '8px 4px',
    fontSize: '13px',
    color: 'var(--text-main)',
  },
  radio: {
    width: '16px',
    height: '16px',
    accentColor: '#10B981',
  },
  feedbackGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
  },
  feedbackInput: {
    backgroundColor: 'var(--bg-main)',
    border: '1px solid var(--border-color)',
    fontSize: '13px',
    color: 'var(--text-main)',
  },
};
