export const styles = {
  container: {
    width: '100%',
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: '340px 1fr',
    gap: '24px',
    alignItems: 'start',
  },
  leftPanel: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '18px',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '12px',
    marginBottom: '4px',
  },
  sectionTitle: {
    fontSize: '15px',
    fontWeight: 700,
    color: 'var(--text-main)',
  },
  textarea: {
    minHeight: '180px',
    resize: 'vertical' as const,
  },
  submitBtn: {
    marginTop: '10px',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
  },
  rightPanel: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: '500px',
  },
  editorHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '16px',
    marginBottom: '20px',
  },
  addBtn: {
    padding: '8px 14px',
    fontSize: '12px',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  questionsList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    maxHeight: '600px',
    overflowY: 'auto' as const,
    paddingRight: '6px',
  },
  qCard: {
    backgroundColor: 'var(--bg-sidebar)',
    border: '1px solid var(--border-color)',
    borderRadius: '16px',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
  },
  qCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '1px solid var(--border-color)',
    paddingBottom: '10px',
  },
  qNumber: {
    fontSize: '13px',
    fontWeight: 800,
    color: 'var(--accent-primary)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  idDisplay: {
    background: 'transparent',
    border: 'none',
    color: 'var(--text-muted)',
    fontFamily: 'monospace',
    fontSize: '11px',
    fontWeight: 700,
    width: '180px',
    textAlign: 'center' as const,
    cursor: 'default',
  },
  deleteBtn: {
    background: 'transparent',
    border: 'none',
    color: '#EF4444',
    cursor: 'pointer',
    opacity: 0.7,
    transition: 'opacity 0.2s',
    '&:hover': {
      opacity: 1,
    },
  },
  qFlexRow: {
    display: 'flex',
    gap: '14px',
  },
  optionsSection: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '12px',
  },
  optRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: 'var(--bg-main)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '4px 10px',
  },
  optLetter: {
    fontSize: '11px',
    fontWeight: 800,
    color: 'var(--text-muted)',
    backgroundColor: 'var(--border-color)',
    width: '20px',
    height: '20px',
    borderRadius: '6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optInput: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    padding: '8px 4px',
    fontSize: '13px',
    outline: 'none',
    color: 'var(--text-main)',
  },
  radio: {
    width: '16px',
    height: '16px',
    accentColor: '#10B981',
    cursor: 'pointer',
  },
  feedbackGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '14px',
  },
};
