export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    width: '100%',
  },
  header: {
    marginBottom: '8px',
  },
  searchCard: {
    padding: '20px 24px',
  },
  searchRow: {
    display: 'flex',
    gap: '12px',
    marginTop: '4px',
  },
  searchInput: {
    flex: 1,
  },
  searchBtn: {
    paddingLeft: '24px',
    paddingRight: '24px',
  },
  centered: {
    textAlign: 'center' as const,
    padding: '60px 40px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '12px',
  },
  emojiIcon: {
    fontSize: '44px',
    opacity: 0.5,
  },
  emptyText: {
    fontSize: '15px',
    fontWeight: '700',
    color: 'var(--text-main)',
  },
  emptySubText: {
    fontSize: '12px',
    color: 'var(--text-muted)',
    maxWidth: '450px',
    lineHeight: '18px',
  },
  loadingText: {
    color: '#6366F1',
    fontWeight: 600,
    fontSize: '14px',
  },
  resultsContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
  },
  statsRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '20px',
  },
  statBox: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
    alignItems: 'center',
  },
  statLbl: {
    fontSize: '11px',
    fontWeight: 700,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  statVal: {
    fontFamily: 'Space Grotesk, sans-serif',
    fontSize: '26px',
    fontWeight: 700,
    color: 'var(--text-main)',
  },
  splitLayout: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '24px',
    alignItems: 'start',
  },
  leftCol: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
  },
  rightCol: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  feedCard: {
    padding: '24px',
  },
  cardTitle: {
    fontSize: '16px',
    marginBottom: '20px',
  },
  timeline: {
    position: 'relative' as const,
    paddingLeft: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
  },
  timelineItem: {
    position: 'relative' as const,
    display: 'flex',
    gap: '16px',
  },
  timelineLine: {
    position: 'absolute' as const,
    left: '-16px',
    top: '24px',
    bottom: '-28px',
    width: '2px',
    backgroundColor: 'var(--border-color)',
  },
  timelineDot: {
    position: 'absolute' as const,
    left: '-22px',
    top: '4px',
    width: '14px',
    height: '14px',
    borderRadius: '7px',
    borderWidth: '2px',
    zIndex: 2,
  },
  dotGreen: {
    backgroundColor: '#064E3B',
    borderColor: '#10B981',
  },
  dotYellow: {
    backgroundColor: '#78350F',
    borderColor: '#F59E0B',
  },
  dotRed: {
    backgroundColor: '#7F1D1D',
    borderColor: '#EF4444',
  },
  timelineContent: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.01)',
    border: '1px solid var(--border-color)',
    borderRadius: '12px',
    padding: '16px',
  },
  timelineHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
  },
  topicName: {
    fontSize: '14px',
    fontWeight: '800',
    color: 'var(--text-main)',
  },
  logMeta: {
    fontSize: '11px',
    color: 'var(--text-muted)',
  },
  badgeSuccess: {
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    color: '#10B981',
    border: '1px solid rgba(16, 185, 129, 0.2)',
  },
  badgeWarning: {
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    color: '#F59E0B',
    border: '1px solid rgba(245, 158, 11, 0.2)',
  },
  badgeDanger: {
    padding: '3px 8px',
    borderRadius: '6px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#EF4444',
    border: '1px solid rgba(239, 68, 68, 0.2)',
  },
};
