export const styles = {
  card: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '16px',
    textAlign: 'left' as const,
    cursor: 'pointer',
    width: '100%',
    transition: 'all 0.2s cubic-bezier(0.16, 1, 0.3, 1)',
    border: '1px solid var(--border-color)',
  },
  cardSelected: {
    borderColor: '#6366F1',
    boxShadow: '0 0 15px rgba(99, 102, 241, 0.15)',
    backgroundColor: 'rgba(99, 102, 241, 0.04)',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    width: '100%',
  },
  avatar: {
    width: '36px',
    height: '36px',
    borderRadius: '10px',
    backgroundColor: 'var(--border-color)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '16px',
    border: '1px solid var(--border-color)',
  },
  nameContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  name: {
    fontSize: '14px',
    fontWeight: 700,
    color: 'var(--text-main)',
    fontFamily: 'monospace',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    maxWidth: '120px',
  },
  badge: {
    fontSize: '10px',
    color: 'var(--text-muted)',
    marginTop: '1px',
    fontWeight: 600,
    textTransform: 'uppercase' as const,
  },
  scoreBadge: {
    padding: '4px 8px',
    borderRadius: '6px',
    fontSize: '12px',
    fontWeight: 800,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '10px',
    paddingTop: '12px',
    borderTop: '1px solid var(--border-color)',
  },
  statItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  statVal: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontWeight: 600,
  },
};
