export const styles = {
  container: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    width: '100%',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subTabGroup: {
    display: 'flex',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid var(--border-color)',
    borderRadius: '10px',
    padding: '4px',
    gap: '4px',
  },
  subTabBtn: {
    padding: '6px 14px',
    border: 'none',
    backgroundColor: 'transparent',
    color: 'var(--text-muted)',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
    fontWeight: 600,
    fontSize: '12px',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  subTabBtnActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    color: 'var(--text-main)',
  },
  refreshBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    border: '1px solid var(--border-color)',
    color: 'var(--text-main)',
    padding: '8px 16px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
  },
  summaryRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '20px',
  },
  summaryCard: {
    padding: '20px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '6px',
  },
  cardLabel: {
    fontSize: '11px',
    fontWeight: 700,
    color: 'var(--text-muted)',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  cardValue: {
    fontFamily: 'Space Grotesk, sans-serif',
    fontSize: '26px',
    fontWeight: 700,
    color: 'var(--text-main)',
  },
  gridSection: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  sectionTitle: {
    fontSize: '16px',
    fontWeight: 700,
    color: 'var(--text-main)',
  },
  studentGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '16px',
  },
  filterBar: {
    padding: '18px 24px',
    display: 'flex',
    alignItems: 'flex-end',
    gap: '20px',
  },
  filterChipContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  filterChip: {
    padding: '8px 14px',
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--accent-primary)',
    borderColor: 'var(--accent-primary-glow)',
    backgroundColor: 'var(--accent-primary-glow)',
  },
  tableContainer: {
    overflowX: 'auto' as const,
    padding: '4px',
  },
  centered: {
    textAlign: 'center' as const,
    padding: '40px',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    textAlign: 'left' as const,
    fontSize: '14px',
  },
  th: {
    padding: '16px 20px',
    borderBottom: '1px solid var(--border-color)',
    color: 'var(--text-muted)',
    fontWeight: 700,
  },
  tr: {
    borderBottom: '1px solid var(--border-color)',
  },
  td: {
    padding: '16px 20px',
    color: 'var(--text-main)',
  },
  studentIdBadge: {
    backgroundColor: 'var(--border-color)',
    padding: '4px 8px',
    borderRadius: '6px',
    fontFamily: 'monospace',
    fontSize: '12px',
    border: '1px solid var(--border-color)',
  },
  scoreCell: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '6px',
  },
  fractionText: {
    fontSize: '11px',
    color: 'var(--text-muted)',
    fontWeight: 500,
  },
  badgeSuccess: {
    padding: '4px 10px',
    borderRadius: '99px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(16, 185, 129, 0.1)',
    color: '#10B981',
    border: '1px solid rgba(16, 185, 129, 0.2)',
  },
  badgeWarning: {
    padding: '4px 10px',
    borderRadius: '99px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(245, 158, 11, 0.1)',
    color: '#F59E0B',
    border: '1px solid rgba(245, 158, 11, 0.2)',
  },
  badgeDanger: {
    padding: '4px 10px',
    borderRadius: '99px',
    fontSize: '10px',
    fontWeight: 700,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    color: '#EF4444',
    border: '1px solid rgba(239, 68, 68, 0.2)',
  },
};
