import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import { ParentSpace } from './ParentSpace';
import { StudentSpace } from './StudentSpace';
import { ParentStudentRegistration, type LinkedStudentProfile } from '../components/parent/ParentStudentRegistration';

describe('Parent and Student Interconnected Flow Integration', () => {
  let originalFetch: typeof global.fetch;

  beforeAll(() => {
    originalFetch = global.fetch;
  });

  afterAll(() => {
    global.fetch = originalFetch;
  });

  beforeEach(() => {
    jest.clearAllMocks();
    localStorage.clear();
    Object.assign(navigator, {
      clipboard: {
        writeText: jest.fn(),
      },
    });
  });

  // ───────────────────────────────────────────────────────────────────────────
  // FLOW 1: Parent Registers Student Account -> Generates & Copies Credentials
  // ───────────────────────────────────────────────────────────────────────────
  it('Flow 1: Parent registers a new student account, copies credentials, and student profile links', async () => {
    const mockStudentData = {
      studentId: 'STU-987654',
      name: 'Juan Dela Cruz',
      email: 'juan.cruz@school.edu.ph',
      accessCode: '789123',
      section: 'Mabini',
    };

    const mockFetch = jest.fn().mockImplementation((url: string) => {
      if (url === '/api/parent/create-student') {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve({ success: true, student: mockStudentData }),
        });
      }
      return Promise.resolve({ ok: true, json: () => Promise.resolve([]) });
    });
    global.fetch = mockFetch as any;

    const mockSelectChild = jest.fn();
    render(<ParentStudentRegistration onSelectStudentForExplorer={mockSelectChild} />);

    // Fill registration form
    fireEvent.change(screen.getByPlaceholderText('e.g. Juan'), { target: { value: 'Juan' } });
    fireEvent.change(screen.getByPlaceholderText('e.g. Dela Cruz'), { target: { value: 'Dela Cruz' } });
    fireEvent.change(screen.getByPlaceholderText('e.g. Mabini, Rizal'), { target: { value: 'Mabini' } });
    fireEvent.change(screen.getByPlaceholderText(/learner email/i), { target: { value: 'juan.cruz@school.edu.ph' } });
    fireEvent.change(screen.getByPlaceholderText(/Choose a secure student password/i), { target: { value: 'SecurePass123!' } });

    // Submit form
    fireEvent.click(screen.getByRole('button', { name: /Register Student Account/i }));

    await waitFor(() => {
      expect(screen.getByText(/Account Created Successfully for Juan Dela Cruz!/i)).toBeInTheDocument();
    });

    // Check credentials box
    expect(screen.getByText('STU-987654')).toBeInTheDocument();
    expect(screen.getByText('789123')).toBeInTheDocument();

    // Test copy buttons for Student ID and Access Code
    const copyIdBtn = screen.getByTitle('Copy Student ID');
    fireEvent.click(copyIdBtn);
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('STU-987654');

    const copyCodeBtn = screen.getByTitle('Copy Access Code');
    fireEvent.click(copyCodeBtn);
    expect(navigator.clipboard.writeText).toHaveBeenCalledWith('789123');

    // Verify student is saved into localStorage for linked children
    const savedLinked = JSON.parse(localStorage.getItem('guro_parent_linked_children') || '[]');
    expect(savedLinked).toHaveLength(1);
    expect(savedLinked[0].studentId).toBe('STU-987654');
    expect(savedLinked[0].accessCode).toBe('789123');

    // Clicking "Explore Child Telemetry Now" triggers explorer navigation
    const exploreBtn = screen.getByRole('button', { name: /Explore Child Telemetry Now/i });
    fireEvent.click(exploreBtn);
    expect(mockSelectChild).toHaveBeenCalledWith('STU-987654', '789123');
  });

  // ───────────────────────────────────────────────────────────────────────────
  // FLOW 2: Student Takes Diagnostic Quiz -> Parent Inspects Synced Telemetry
  // ───────────────────────────────────────────────────────────────────────────
  it('Flow 2: Student completes diagnostic quest and Parent monitors real-time telemetry in ParentSpace', async () => {
    const studentUser = {
      name: 'Juan Dela Cruz',
      email: 'juan.cruz@school.edu.ph',
      userId: 'STU-987654',
    };

    // 1. Render Student Space for Juan
    const mockExit = jest.fn();
    const mockLogout = jest.fn();

    const { unmount: unmountStudent } = render(
      <StudentSpace
        currentUser={studentUser}
        onExit={mockExit}
        onLogout={mockLogout}
        isDarkMode={false}
        onToggleTheme={jest.fn()}
      />
    );

    // Verify student is on dashboard
    expect(screen.getAllByText(/Welcome back, Juan Dela Cruz!/i).length).toBeGreaterThan(0);
    unmountStudent();

    // 2. Mock synced progress events generated by Juan's learning session
    const juanTelemetryEvents = [
      {
        studentId: 'STU-987654',
        eventId: 'EVT-001',
        subject: 'Mathematics',
        gradeLevel: 4,
        topic: 'Fractions',
        score: 9,
        totalQuestions: 10,
        timestamp: new Date().toISOString(),
      },
      {
        studentId: 'STU-987654',
        eventId: 'EVT-002',
        subject: 'English',
        gradeLevel: 4,
        topic: 'Figurative Language',
        score: 8,
        totalQuestions: 10,
        timestamp: new Date().toISOString(),
      },
    ];

    const mockFetch = jest.fn().mockImplementation((url: string) => {
      if (url.includes('studentId=STU-987654')) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve(juanTelemetryEvents),
        });
      }
      return Promise.resolve({ ok: true, json: () => Promise.resolve([]) });
    });
    global.fetch = mockFetch as any;

    // 3. Parent opens Parent Space and searches for Juan's ID & Access Code
    const { rerender } = render(
      <ParentSpace
        lastUpdatedCell={null}
        activeSubTab="parent-overview"
      />
    );

    fireEvent.change(screen.getByPlaceholderText(/e\.g\. Cruz, Juan or Student ID/i), {
      target: { value: 'STU-987654' },
    });
    fireEvent.change(screen.getByPlaceholderText('e.g. 123456'), {
      target: { value: '789123' },
    });
    fireEvent.click(screen.getByRole('button', { name: /Search Reports/i }));

    // Await Parent Overview metrics
    await waitFor(() => {
      expect(screen.getByText('Completed Quests')).toBeInTheDocument();
    });

    expect(screen.getByText('2')).toBeInTheDocument(); // 2 quests
    expect(screen.getByText('85%')).toBeInTheDocument(); // (90 + 80) / 2
    expect(screen.getByText('Advanced')).toBeInTheDocument();
    expect(screen.getByText(/Learning Overview for STU-987654/i)).toBeInTheDocument();

    // 4. Test Switching to Activity & Badges view
    rerender(
      <ParentSpace
        lastUpdatedCell={null}
        activeSubTab="parent-badges"
      />
    );

    await waitFor(() => {
      expect(screen.getByText(/Practice Habit & Milestones/i)).toBeInTheDocument();
      expect(screen.getByText(/Achievements Unlocked/i)).toBeInTheDocument();
    });

    // 5. Test Switching to Practice Timeline view with Subject Filters
    rerender(
      <ParentSpace
        lastUpdatedCell={null}
        activeSubTab="parent-timeline"
      />
    );

    await waitFor(() => {
      expect(screen.getByText(/Practice Timeline History/i)).toBeInTheDocument();
      expect(screen.getByText(/Showing 2 sessions/i)).toBeInTheDocument();
    });

    // Click Math filter button in Timeline
    const mathFilterBtn = screen.getByRole('button', { name: 'Math' });
    fireEvent.click(mathFilterBtn);
    expect(screen.getByText(/Showing 1 session/i)).toBeInTheDocument();

    // Click English filter button in Timeline
    const engFilterBtn = screen.getByRole('button', { name: 'English' });
    fireEvent.click(engFilterBtn);
    expect(screen.getByText(/Showing 1 session/i)).toBeInTheDocument();

    // Click All filter button in Timeline
    const allFilterBtn = screen.getByRole('button', { name: 'All' });
    fireEvent.click(allFilterBtn);
    expect(screen.getByText(/Showing 2 sessions/i)).toBeInTheDocument();
  });

  // ───────────────────────────────────────────────────────────────────────────
  // FLOW 3: Multi-Child Fast Switching via Quick Pills
  // ───────────────────────────────────────────────────────────────────────────
  it('Flow 3: Parent switches seamlessly between multiple linked children', async () => {
    const linkedProfiles: LinkedStudentProfile[] = [
      {
        studentId: 'STU-111',
        name: 'Juan Dela Cruz',
        email: 'juan@school.ph',
        accessCode: '111222',
        createdAt: new Date().toISOString(),
      },
      {
        studentId: 'STU-222',
        name: 'Maria Clara',
        email: 'maria@school.ph',
        accessCode: '333444',
        createdAt: new Date().toISOString(),
      },
    ];

    localStorage.setItem('guro_parent_linked_children', JSON.stringify(linkedProfiles));

    const mockFetch = jest.fn().mockImplementation((url: string) => {
      if (url.includes('studentId=STU-111')) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve([
            { studentId: 'STU-111', eventId: 'E1', subject: 'Mathematics', gradeLevel: 4, topic: 'Fractions', score: 10, totalQuestions: 10, timestamp: new Date().toISOString() },
          ]),
        });
      }
      if (url.includes('studentId=STU-222')) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve([
            { studentId: 'STU-222', eventId: 'E2', subject: 'English', gradeLevel: 5, topic: 'Adjectives', score: 6, totalQuestions: 10, timestamp: new Date().toISOString() },
          ]),
        });
      }
      return Promise.resolve({ ok: true, json: () => Promise.resolve([]) });
    });
    global.fetch = mockFetch as any;

    render(<ParentSpace lastUpdatedCell={null} activeSubTab="parent-overview" />);

    // Fast-switch pills are visible
    expect(screen.getByText('Juan Dela Cruz')).toBeInTheDocument();
    expect(screen.getByText('Maria Clara')).toBeInTheDocument();

    // Click Maria Clara pill
    const mariaPill = screen.getByRole('button', { name: /Maria Clara/i });
    fireEvent.click(mariaPill);

    await waitFor(() => {
      expect(screen.getByText(/Learning Overview for STU-222/i)).toBeInTheDocument();
      expect(screen.getByText('60%')).toBeInTheDocument();
    });

    // Click Juan Dela Cruz pill
    const juanPill = screen.getByRole('button', { name: /Juan Dela Cruz/i });
    fireEvent.click(juanPill);

    await waitFor(() => {
      expect(screen.getByText(/Learning Overview for STU-111/i)).toBeInTheDocument();
      expect(screen.getByText('100%')).toBeInTheDocument();
    });
  });
});
